// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"
)

type Post struct {
	ID        int64
	AuthorID  int64
	Url       string
	Title     sql.NullString
	Content   sql.NullString
	Slug      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PostTag struct {
	PostID int64
	TagID  int64
}

type Tag struct {
	ID   int64
	Name string
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
